name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      uses: mr-smithers-excellent/docker-build-push@v6
      with: 
          image: compilereg/itioswebapp
          registry: docker.io
          dockerfile: Dockerfile
          username: "${{ secrets.REPO_USER }}"
          password: "${{ secrets.REPO_PASS }}"
          tags: latest
